nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']   # Autoriser toutes les origines
        allow_headers: ['*']  # Autoriser tous les headers
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'] # Autoriser toutes les m√©thodes HTTP
        expose_headers: []
        max_age: 3600
    paths:
        '^/': 
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']


